version: "3"

vars:
  PROGRAM: template

tasks:
  deps:
    cmds:
      - go mod tidy -v

  update:
    deps: [htmx-update, prompt-update, generate]
    cmds:
      - go get -u
      - go get -u tool
      - go mod tidy -v

  generate:
    deps: [sqlc, templ, tailwind]

  sqlc:
    cmds:
      - go tool sqlc generate

  templ:
    cmds:
      - go tool templ generate

  setup:
    cmds:
      - npm i --no-fund -D tailwindcss@latest @tailwindcss/cli
      - npm i --no-fund -D @tailwindcss/typography
      - npm i --no-fund -D daisyui@latest
      - npm --no-fund audit fix

  build:
    aliases: [default]
    deps: [deps, generate]
    env:
      CGO_ENABLED: 0
    cmds:
      - go fmt ./...
      - go tool gofumpt -l -w .
      - go tool templ fmt .
      - go vet ./...
      - go build -o {{.PROGRAM}}

  test:
    deps: [deps, generate]
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -race -cover ./...

  run:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug -config config.json

  dev:
    deps: [build]
    cmds:
      - go tool air

  configcheck:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -configcheck -config config.json

  htmx-update:
    cmds:
      - wget -nv -O ./internal/server/assets/web/scripts/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js

  tailwind:
    cmds:
      - npx @tailwindcss/cli -i ./internal/server/assets/web/css/input.css -o ./internal/server/assets/web/css/style.min.css --minify

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

  prompt-update:
    # https://daisyui.com/docs/editor/vscode/
    # https://github.com/github/awesome-copilot/tree/main/instructions
    cmds:
      - curl -sSfL https://daisyui.com/llms.txt --create-dirs -o .github/instructions/daisyui.instructions.md
      - curl -sSfL https://raw.githubusercontent.com/github/awesome-copilot/refs/heads/main/instructions/go.instructions.md --create-dirs -o .github/instructions/go.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/containerization-docker-best-practices.instructions.md --create-dirs -o .github/instructions/containerization-docker-best-practices.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/devops-core-principles.instructions.md --create-dirs -o .github/instructions/devops-core-principles.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/github-actions-ci-cd-best-practices.instructions.md --create-dirs -o .github/instructions/github-actions-ci-cd-best-practices.instructions.md
      - curl -sSfL https://github.com/github/awesome-copilot/raw/refs/heads/main/instructions/security-and-owasp.instructions.md --create-dirs -o .github/instructions/security-and-owasp.instructions.md

  tag:
    cmds:
      - git tag -a "${TAG}" -m "${TAG}"
      - git push origin "${TAG}"
    preconditions:
      - sh: '[[ -n "${TAG}" ]]'
        msg: "Please set the TAG environment variable"
