version: "3"

vars:
  PROGRAM: template

tasks:
  deps:
    cmds:
      - go mod tidy -v

  update:
    deps: [htmx-update, generate]
    cmds:
      - go get -u
      - go get -u tool
      - go mod tidy -v

  generate:
    deps: [sqlc, templ, tailwind]

  sqlc:
    cmds:
      - go tool sqlc generate

  templ:
    cmds:
      - go tool templ generate

  setup:
    cmds:
      - npm i -D tailwindcss@latest @tailwindcss/cli
      - npm i -D @tailwindcss/typography
      - npm i -D daisyui@latest
      - npm audit fix

  build:
    aliases: [default]
    deps: [deps, generate]
    env:
      CGO_ENABLED: 0
    cmds:
      - go fmt ./...
      - go tool gofumpt -l -w .
      - go tool templ fmt .
      - go vet ./...
      - go build -o {{.PROGRAM}}

  test:
    deps: [deps, generate]
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -race -cover ./...

  run:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug -config config.json

  dev:
    deps: [build]
    cmds:
      - go tool air

  configcheck:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -configcheck -config config.json

  htmx-update:
    cmds:
      - wget -nv -O ./internal/server/assets/web/scripts/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js

  tailwind:
    cmds:
      - npx @tailwindcss/cli -i ./internal/server/assets/web/css/input.css -o ./internal/server/assets/web/css/style.min.css --minify

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ .GOPATH }}/bin
      - golangci-lint --version
    vars:
      GOPATH:
        sh: go env GOPATH

  tag:
    cmds:
      - git tag -a "${TAG}" -m "${TAG}"
      - git push origin "${TAG}"
    preconditions:
      - sh: '[[ -n "${TAG}" ]]'
        msg: "Please set the TAG environment variable"
