name: Hadolint
on:
  push:
    paths:
      - "**/Dockerfile"
  pull_request:
  workflow_dispatch:
jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-hadolint@v1
        with:
          fail_level: any
          reporter: github-pr-review
