name: yamllint
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_level: any
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable, line-length: disable}}" .'
